# Auth Example

```yaml
include:
  - auth.variables.yaml
  - auth.variables.private.yaml
test: auth
post: $host/api/auth
body: |
  {
    "Username": "$admin_username",
    "Password": "$admin_password"
  }
success:
  # Capture the token from the response (via JSONPath)
  # and store it in a variable for use in subsequent requests.
  token: $.result.token
```

```yaml
test: verify_token
depends_on: auth
get: $host/api/something-protected
authorization: Bearer $token
```
