# Auth Example

```yaml
include:
  - auth.variables.yaml
  - auth.variables.private.yaml
```

```yaml
test: auth
post: $host/api/auth
body: |
  {
    "Username": "$admin_username",
    "Password": "$admin_password"
  }
expect:
  status: 200
capture:
  # Capture the token from the response (via JSONPath)
  # and store it in a variable for use in subsequent requests.
  token: $.result.token
```

```yaml
test: verify_token
requires: auth
get: $host/api/something-protected
headers:
  authorization: Bearer $token
```
